platform :ios, '10.0'

target 'EthereumWallet' do
  	use_frameworks!

    pod 'JetLib', :git => 'https://github.com/vbenkevich/ios_swift_utils.git', tag: '0.1.0'
    pod 'DITranquillity'
    pod 'Geth'
    pod 'TrezorCrypto'
end
